name: Deploy Node.js Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install express body-parser node-fetch dotenv

      - name: Set up environment variables
        run: echo "EMAIL_TOKEN=${{ secrets.EMAIL_TOKEN }}" >> $GITHUB_ENV

      - name: Start server
        run: node server.js &
