name: Send Test Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email address to send the test email to'
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        env:
          ZOHO_EMAIL: noreply@zeeps.me
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
          EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }} 
        run: |
          echo "Sending email to ${{ github.event.inputs.email }} from $ZOHO_EMAIL"
          echo -e "Subject: Test Email\n\nThis is a test email from Zeeps." | ssmtp -v ${{ github.event.inputs.email }}
